import './globals.css';
import SideNav from './ui/sidenav';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { SettingsProvider } from '@/app/ui/settings/SettingsContext';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SettingsProvider>
      <body>    
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
      
      <div className="w-full flex-none md:w-64">
        <SideNav />
      </div>
      
      <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
    </div></body>
    </SettingsProvider>
    </html>
  )
}
